
---

- name: change password for user
  hosts: all
  vars_files:
   - var_newpass.yaml
  become: yes
  tasks:
    - name: change password for "{{username}}"
      user:
       name: "{{username}}"
       update_password: always
       password: "{{new_password | password_hash('sha512')}}"
      with_items: "{{ lookup('file', 'ip_list.txt').splitlines() }}"
